language: python

sudo: false

python:
  - "3.4"

cache: pip

install:
  - git clone https://github.com/opencontrol/schemas
  - travis_retry pip install pytest
  - travis_retry pip install pykwalify
  - travis_retry pip install pyyaml

script:
  - py.test
